#!/usr/bin/env bun
/**
 * Generates src/tokens.ts from theme.css.
 *
 * theme.css is the single source of truth for brand colors (Tailwind v4
 * and shadcn consume CSS vars directly). tokens.ts is the derived hex
 * snapshot used by non-CSS contexts (Satori OG images, logo exports,
 * email templates). Re-run after editing theme.css:
 *
 *   bun run brand:build
 *
 * CI verifies the generated file matches committed tokens.ts.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { converter, formatHex, parse } from "culori";

const HERE = new URL(".", import.meta.url).pathname;
const BRAND_ROOT = resolve(HERE, "..");
const THEME_CSS = resolve(BRAND_ROOT, "theme.css");
const TOKENS_TS = resolve(BRAND_ROOT, "src", "tokens.ts");

const rawCss = readFileSync(THEME_CSS, "utf8");
const css = rawCss.replace(/\/\*[\s\S]*?\*\//g, "");

// ── block extraction ────────────────────────────────────────────────────────

const SELECTOR_RE = /(?<selector>[^{}]+?)\s*\{(?<body>[^{}]*)\}/g;
const blocks: Record<string, string> = {};
for (const match of css.matchAll(SELECTOR_RE)) {
	const selector = match.groups?.selector?.trim() ?? "";
	const body = match.groups?.body ?? "";
	if (!selector || selector.startsWith("@")) continue;
	const normalized = selector.replace(/\s+/g, " ");
	blocks[normalized] = (blocks[normalized] ?? "") + body;
}

const rootBlock = blocks[":root"];
const lightBlock = Object.entries(blocks)
	.filter(([k]) => k.includes(".light") || k.includes('data-theme="light"'))
	.map(([, v]) => v)
	.join("\n");

if (!rootBlock) throw new Error("theme.css: `:root` block not found");
if (!lightBlock) throw new Error("theme.css: light block not found");

// ── var extraction ──────────────────────────────────────────────────────────

function extractVar(block: string, name: string): string {
	const re = new RegExp(String.raw`--${name}\s*:\s*([^;]+);`);
	const m = block.match(re);
	if (!m) throw new Error(`theme.css: --${name} not found`);
	return m[1].trim();
}

function oklchCoords(raw: string): string {
	const m = raw.match(/^oklch\(\s*([^)/]+?)\s*(?:\/[^)]*)?\)$/i);
	if (!m) throw new Error(`Expected oklch(...), got: ${raw}`);
	return m[1].replace(/\s+/g, " ").trim();
}

const toRgb = converter("rgb");
function oklchToHex(raw: string): string {
	const parsed = parse(raw);
	if (!parsed) throw new Error(`Could not parse color: ${raw}`);
	const rgb = toRgb(parsed);
	if (!rgb) throw new Error(`Could not convert to rgb: ${raw}`);
	const hex = formatHex(rgb);
	if (!hex) throw new Error(`Could not format hex: ${raw}`);
	return hex.toUpperCase();
}

function token(block: string, name: string) {
	const raw = extractVar(block, name);
	return { oklch: oklchCoords(raw), hex: oklchToHex(raw) };
}

// ── build tokens object ─────────────────────────────────────────────────────

const colors = {
	primary: token(rootBlock, "primary"),
	secondary: token(rootBlock, "secondary"),
	accent: token(rootBlock, "accent"),
	ring: token(rootBlock, "ring"),
	houses: {
		ai: token(rootBlock, "house-ai"),
		biotech: token(rootBlock, "house-biotech"),
		hardware: token(rootBlock, "house-hardware"),
		space: token(rootBlock, "house-space"),
	},
	surface: {
		dark: {
			bg: token(rootBlock, "background"),
			fg: token(rootBlock, "foreground"),
			card: token(rootBlock, "card"),
			muted: token(rootBlock, "muted"),
		},
		light: {
			bg: token(lightBlock, "background"),
			fg: token(lightBlock, "foreground"),
			card: token(lightBlock, "card"),
			muted: token(lightBlock, "muted"),
		},
	},
	destructive: token(rootBlock, "destructive"),
};

// ── emit tokens.ts ──────────────────────────────────────────────────────────

function renderToken(t: { oklch: string; hex: string }, indent: string): string {
	return `{\n${indent}\toklch: "${t.oklch}",\n${indent}\thex: "${t.hex}",\n${indent}}`;
}

const out = `/**
 * Brand color tokens — hex snapshot of theme.css (Foundry direction).
 *
 * GENERATED by \`bun run brand:build\` from \`packages/brand/theme.css\`.
 * Do not edit by hand. theme.css is the single source of truth; this file
 * exists only for non-CSS contexts (Satori OG images, logo exports, email
 * templates) that cannot read CSS variables at runtime.
 */

export const colors = {
	primary: ${renderToken(colors.primary, "\t")},
	secondary: ${renderToken(colors.secondary, "\t")},
	accent: ${renderToken(colors.accent, "\t")},
	ring: ${renderToken(colors.ring, "\t")},
	houses: {
		ai: ${renderToken(colors.houses.ai, "\t\t")},
		biotech: ${renderToken(colors.houses.biotech, "\t\t")},
		hardware: ${renderToken(colors.houses.hardware, "\t\t")},
		space: ${renderToken(colors.houses.space, "\t\t")},
	},
	surface: {
		dark: {
			bg: ${renderToken(colors.surface.dark.bg, "\t\t\t")},
			fg: ${renderToken(colors.surface.dark.fg, "\t\t\t")},
			card: ${renderToken(colors.surface.dark.card, "\t\t\t")},
			muted: ${renderToken(colors.surface.dark.muted, "\t\t\t")},
		},
		light: {
			bg: ${renderToken(colors.surface.light.bg, "\t\t\t")},
			fg: ${renderToken(colors.surface.light.fg, "\t\t\t")},
			card: ${renderToken(colors.surface.light.card, "\t\t\t")},
			muted: ${renderToken(colors.surface.light.muted, "\t\t\t")},
		},
	},
	destructive: ${renderToken(colors.destructive, "\t")},
} as const;

export type ColorToken = typeof colors;
`;

writeFileSync(TOKENS_TS, out);
console.log(`✓ Wrote ${TOKENS_TS}`);
