/**
 * Brand color tokens — hex snapshot of theme.css (Foundry direction).
 *
 * GENERATED by `bun run brand:build` from `packages/brand/theme.css`.
 * Do not edit by hand. theme.css is the single source of truth; this file
 * exists only for non-CSS contexts (Satori OG images, logo exports, email
 * templates) that cannot read CSS variables at runtime.
 */

export const colors = {
	primary: {
		oklch: "0.53 0.24 305",
		hex: "#8E2CD7",
	},
	secondary: {
		oklch: "0.72 0.18 55",
		hex: "#F77F00",
	},
	accent: {
		oklch: "0.16 0.035 310",
		hex: "#120918",
	},
	ring: {
		oklch: "0.58 0.22 305",
		hex: "#9A49E0",
	},
	houses: {
		ai: {
			oklch: "0.68 0.26 358",
			hex: "#FF2898",
		},
		biotech: {
			oklch: "0.73 0.23 150",
			hex: "#00CD4E",
		},
		hardware: {
			oklch: "0.68 0.23 30",
			hex: "#FF4834",
		},
		space: {
			oklch: "0.65 0.2 230",
			hex: "#00A0F0",
		},
	},
	surface: {
		dark: {
			bg: {
				oklch: "0.07 0.02 315",
				hex: "#020103",
			},
			fg: {
				oklch: "0.92 0.008 55",
				hex: "#E9E3E0",
			},
			card: {
				oklch: "0.11 0.028 312",
				hex: "#07020B",
			},
			muted: {
				oklch: "0.15 0.02 315",
				hex: "#0E0911",
			},
		},
		light: {
			bg: {
				oklch: "0.975 0.006 85",
				hex: "#F9F6F2",
			},
			fg: {
				oklch: "0.18 0.09 280",
				hex: "#0E0637",
			},
			card: {
				oklch: "0.94 0.015 275",
				hex: "#E8EBF6",
			},
			muted: {
				oklch: "0.91 0.02 275",
				hex: "#DDE1EF",
			},
		},
	},
	destructive: {
		oklch: "0.55 0.22 27",
		hex: "#D40C1A",
	},
} as const;

export type ColorToken = typeof colors;
